apiVersion: v1
kind: List
items:
# Service Account for appoptics-agent-k8s
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: appoptics-agent-serviceaccount
    namespace: kube-system
# Create ClusterRole that enables appoptics-agent-k8s to access requisite kube-api resources
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: appoptics-agent-clusterrole
  rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["*"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
# Bind the appoptics-agent-clusterrole with the appoptics-agent-serviceaccount we created above
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: appoptics-agent-clusterrolebinding
  subjects:
  - kind: ServiceAccount
    name: appoptics-agent-serviceaccount
    namespace: kube-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: appoptics-agent-clusterrole
