apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: swisnap-agent-ds
  namespace: kube-system
  labels:
    daemon: swisnap-agent-ds
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: swisnap-agent-ds
      labels:
        daemon: swisnap-agent-ds
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: swisnap-agent-ds
        image: 'solarwinds/solarwinds-snap-agent-docker:1.1.0'
        imagePullPolicy: Always
        env:
          - name: APPOPTICS_TOKEN
            value: 'APPOPTICS_TOKEN'
          - name: APPOPTICS_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SWISNAP_ENABLE_APACHE
            value: 'false'
          - name: SWISNAP_ENABLE_DOCKER
            value: 'true'
          - name: SWISNAP_ENABLE_ELASTICSEARCH
            value: 'false'
          - name: SWISNAP_ENABLE_KUBERNETES
            value: 'false'
          - name: SWISNAP_ENABLE_MESOS
            value: 'false'
          - name: SWISNAP_ENABLE_MONGODB
            value: 'false'
          - name: SWISNAP_ENABLE_MYSQL
            value: 'false'
          - name: SWISNAP_ENABLE_RABBITMQ
            value: 'false'
          - name: SWISNAP_ENABLE_STATSD
            value: 'false'
          - name: SWISNAP_ENABLE_ZOOKEEPER
            value: 'false'
          - name: SWISNAP_DISABLE_HOSTAGENT
            value: 'false'
          - name: HOST_PROC
            value: '/host/proc'
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: cgroup
            mountPath: /sys/fs/cgroup
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
